package com.example.myproject;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.TextFileProperty;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Upload;

public class Editor extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private OptionGroup optionGroup_1;
	@AutoGenerated
	private Upload upload_1;
	@AutoGenerated
	private TextArea textArea_1;
	@AutoGenerated
	private RichTextArea richTextArea_2;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Editor() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public void setPropertyDataSource(TextFileProperty textFileProperty) {
		// TODO Auto-generated method stub
		richTextArea_2.setPropertyDataSource(textFileProperty);
		textArea_1.setPropertyDataSource(textFileProperty);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		mainLayout.addComponent(tabSheet_1, "top:20.0px;left:20.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("400px");
		tabSheet_1.setHeight("500px");
		
		// richTextArea_2
		richTextArea_2 = new RichTextArea();
		richTextArea_2.setImmediate(false);
		richTextArea_2.setWidth("100.0%");
		richTextArea_2.setHeight("100.0%");
		tabSheet_1.addTab(richTextArea_2, "Tab", null);
		
		// textArea_1
		textArea_1 = new TextArea();
		textArea_1.setImmediate(false);
		textArea_1.setWidth("100.0%");
		textArea_1.setHeight("100.0%");
		tabSheet_1.addTab(textArea_1, "Tab", null);
		
		// upload_1
		upload_1 = new Upload();
		upload_1.setImmediate(false);
		upload_1.setWidth("-1px");
		upload_1.setHeight("28px");
		tabSheet_1.addTab(upload_1, "Tab", null);
		
		// optionGroup_1
		optionGroup_1 = new OptionGroup();
		optionGroup_1.setImmediate(false);
		optionGroup_1.setWidth("-1px");
		optionGroup_1.setHeight("-1px");
		tabSheet_1.addTab(optionGroup_1, "Tab", null);
		
		return tabSheet_1;
	}

}
